name: valheim
on:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - ".github/workflows/valheim.yml"
      - "valheim/**"
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: "Force rebuild even if tag already exist"
        required: false
        default: "false"

jobs:
  set-outputs:
    name: Set Outputs

    runs-on: ubuntu-latest

    outputs:
      STEAM_APP_NAME: ${{ steps.compute.outputs.STEAM_APP_NAME }}
      STEAM_APP_ID: ${{ steps.compute.outputs.STEAM_APP_ID }}
      BUILD_ID: ${{ steps.compute.outputs.BUILD_ID }}

    steps:
      - id: compute
        run: |
          STEAM_APP_NAME=valheim
          STEAM_APP_ID=896660
          echo "::set-output name=STEAM_APP_NAME::$STEAM_APP_NAME"
          echo "::set-output name=STEAM_APP_ID::$STEAM_APP_ID"
          BUILD_ID=$(docker run steamcmd/steamcmd:ubuntu +login anonymous +app_info_update 1 +app_info_print ${STEAM_APP_ID} +quit | grep -EA 1000 "^\s+\"branches\"$" | grep -EA 5 "^\s+\"public\"$" | grep -m 1 -EB 10 "^\s+}$" | grep -E "^\s+\"buildid\"\s+" | tr '[:blank:]"' ' ' | tr -s ' ' | cut -d' ' -f3)
          if ! curl --silent -f -lSL https://hub.docker.com/v2/repositories/goblinslab/steam-dedicated-server/tags/${STEAM_APP_NAME}-${BUILD_ID} || ${{ github.event.inputs.force_rebuild }} == "true"
          then
            echo "::set-output name=BUILD_ID::${BUILD_ID}"
            echo "There is a new version of ${STEAM_APP_NAME} : ${BUILD_ID}"
          fi

  build:
    runs-on: ubuntu-latest
    if: needs.set-outputs.outputs.BUILD_ID != '' || github.event.inputs.force_rebuild == 'true'

    needs: [set-outputs]
    
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            STEAM_APP_NAME=${{ needs.set-outputs.outputs.STEAM_APP_NAME }}
            STEAM_APP_ID=${{ needs.set-outputs.outputs.STEAM_APP_ID }}
          tags: |
            goblinslab/steam-dedicated-server:valheim-latest
            goblinslab/steam-dedicated-server:valheim-${{ needs.set-outputs.outputs.BUILD_ID }}
